// Messi is a soccer player with goals in three leagues:

// LaLiga
// Copa del Rey
// Champions
// Complete the function to return his total number of goals in all three leagues.


function goals (a, b ,c) {
    return a + b + c
}


// numbers, will never be any other data type
// return sum of all three leagues, input will always be valid
// 5, 10, 2  -->  17
// keep it simple, for the sum use the arithmetic operator '+'
    // add a,b,c together
