// You are running the calculation 2 + 2 * 2 + 2 * 2 and expect to get the answer 32 but instead the function keeps returning 10. Fix the function to make it return 32 without changing the number or the operators.
// parenthesis to the addition operator 
// PEMDAS - parenthesis, exponents, multiplication/division, addition/subtraction


function orderOperations () {
    return (2 + 2) * (2 + 2) * 2
}

